# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/enigma/Documents/C++/Updated/Rahbar-e-Sukhan

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/enigma/Documents/C++/Updated/Rahbar-e-Sukhan

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/enigma/Documents/C++/Updated/Rahbar-e-Sukhan/CMakeFiles /home/enigma/Documents/C++/Updated/Rahbar-e-Sukhan//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/enigma/Documents/C++/Updated/Rahbar-e-Sukhan/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Rahbar-e-Sukhan

# Build rule for target.
Rahbar-e-Sukhan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Rahbar-e-Sukhan
.PHONY : Rahbar-e-Sukhan

# fast build rule for target.
Rahbar-e-Sukhan/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/build
.PHONY : Rahbar-e-Sukhan/fast

#=============================================================================
# Target rules for targets named Rahbar-e-Sukhan_autogen

# Build rule for target.
Rahbar-e-Sukhan_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Rahbar-e-Sukhan_autogen
.PHONY : Rahbar-e-Sukhan_autogen

# fast build rule for target.
Rahbar-e-Sukhan_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan_autogen.dir/build.make CMakeFiles/Rahbar-e-Sukhan_autogen.dir/build
.PHONY : Rahbar-e-Sukhan_autogen/fast

Rahbar-e-Sukhan_autogen/EWIEGA46WW/qrc_qml.o: Rahbar-e-Sukhan_autogen/EWIEGA46WW/qrc_qml.cpp.o

.PHONY : Rahbar-e-Sukhan_autogen/EWIEGA46WW/qrc_qml.o

# target to build an object file
Rahbar-e-Sukhan_autogen/EWIEGA46WW/qrc_qml.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/Rahbar-e-Sukhan_autogen/EWIEGA46WW/qrc_qml.cpp.o
.PHONY : Rahbar-e-Sukhan_autogen/EWIEGA46WW/qrc_qml.cpp.o

Rahbar-e-Sukhan_autogen/EWIEGA46WW/qrc_qml.i: Rahbar-e-Sukhan_autogen/EWIEGA46WW/qrc_qml.cpp.i

.PHONY : Rahbar-e-Sukhan_autogen/EWIEGA46WW/qrc_qml.i

# target to preprocess a source file
Rahbar-e-Sukhan_autogen/EWIEGA46WW/qrc_qml.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/Rahbar-e-Sukhan_autogen/EWIEGA46WW/qrc_qml.cpp.i
.PHONY : Rahbar-e-Sukhan_autogen/EWIEGA46WW/qrc_qml.cpp.i

Rahbar-e-Sukhan_autogen/EWIEGA46WW/qrc_qml.s: Rahbar-e-Sukhan_autogen/EWIEGA46WW/qrc_qml.cpp.s

.PHONY : Rahbar-e-Sukhan_autogen/EWIEGA46WW/qrc_qml.s

# target to generate assembly for a file
Rahbar-e-Sukhan_autogen/EWIEGA46WW/qrc_qml.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/Rahbar-e-Sukhan_autogen/EWIEGA46WW/qrc_qml.cpp.s
.PHONY : Rahbar-e-Sukhan_autogen/EWIEGA46WW/qrc_qml.cpp.s

Rahbar-e-Sukhan_autogen/mocs_compilation.o: Rahbar-e-Sukhan_autogen/mocs_compilation.cpp.o

.PHONY : Rahbar-e-Sukhan_autogen/mocs_compilation.o

# target to build an object file
Rahbar-e-Sukhan_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/Rahbar-e-Sukhan_autogen/mocs_compilation.cpp.o
.PHONY : Rahbar-e-Sukhan_autogen/mocs_compilation.cpp.o

Rahbar-e-Sukhan_autogen/mocs_compilation.i: Rahbar-e-Sukhan_autogen/mocs_compilation.cpp.i

.PHONY : Rahbar-e-Sukhan_autogen/mocs_compilation.i

# target to preprocess a source file
Rahbar-e-Sukhan_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/Rahbar-e-Sukhan_autogen/mocs_compilation.cpp.i
.PHONY : Rahbar-e-Sukhan_autogen/mocs_compilation.cpp.i

Rahbar-e-Sukhan_autogen/mocs_compilation.s: Rahbar-e-Sukhan_autogen/mocs_compilation.cpp.s

.PHONY : Rahbar-e-Sukhan_autogen/mocs_compilation.s

# target to generate assembly for a file
Rahbar-e-Sukhan_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/Rahbar-e-Sukhan_autogen/mocs_compilation.cpp.s
.PHONY : Rahbar-e-Sukhan_autogen/mocs_compilation.cpp.s

src/Isqat.o: src/Isqat.cpp.o

.PHONY : src/Isqat.o

# target to build an object file
src/Isqat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/Isqat.cpp.o
.PHONY : src/Isqat.cpp.o

src/Isqat.i: src/Isqat.cpp.i

.PHONY : src/Isqat.i

# target to preprocess a source file
src/Isqat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/Isqat.cpp.i
.PHONY : src/Isqat.cpp.i

src/Isqat.s: src/Isqat.cpp.s

.PHONY : src/Isqat.s

# target to generate assembly for a file
src/Isqat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/Isqat.cpp.s
.PHONY : src/Isqat.cpp.s

src/Lafz.o: src/Lafz.cpp.o

.PHONY : src/Lafz.o

# target to build an object file
src/Lafz.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/Lafz.cpp.o
.PHONY : src/Lafz.cpp.o

src/Lafz.i: src/Lafz.cpp.i

.PHONY : src/Lafz.i

# target to preprocess a source file
src/Lafz.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/Lafz.cpp.i
.PHONY : src/Lafz.cpp.i

src/Lafz.s: src/Lafz.cpp.s

.PHONY : src/Lafz.s

# target to generate assembly for a file
src/Lafz.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/Lafz.cpp.s
.PHONY : src/Lafz.cpp.s

src/Meter.o: src/Meter.cpp.o

.PHONY : src/Meter.o

# target to build an object file
src/Meter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/Meter.cpp.o
.PHONY : src/Meter.cpp.o

src/Meter.i: src/Meter.cpp.i

.PHONY : src/Meter.i

# target to preprocess a source file
src/Meter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/Meter.cpp.i
.PHONY : src/Meter.cpp.i

src/Meter.s: src/Meter.cpp.s

.PHONY : src/Meter.s

# target to generate assembly for a file
src/Meter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/Meter.cpp.s
.PHONY : src/Meter.cpp.s

src/Satoor.o: src/Satoor.cpp.o

.PHONY : src/Satoor.o

# target to build an object file
src/Satoor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/Satoor.cpp.o
.PHONY : src/Satoor.cpp.o

src/Satoor.i: src/Satoor.cpp.i

.PHONY : src/Satoor.i

# target to preprocess a source file
src/Satoor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/Satoor.cpp.i
.PHONY : src/Satoor.cpp.i

src/Satoor.s: src/Satoor.cpp.s

.PHONY : src/Satoor.s

# target to generate assembly for a file
src/Satoor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/Satoor.cpp.s
.PHONY : src/Satoor.cpp.s

src/Satr.o: src/Satr.cpp.o

.PHONY : src/Satr.o

# target to build an object file
src/Satr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/Satr.cpp.o
.PHONY : src/Satr.cpp.o

src/Satr.i: src/Satr.cpp.i

.PHONY : src/Satr.i

# target to preprocess a source file
src/Satr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/Satr.cpp.i
.PHONY : src/Satr.cpp.i

src/Satr.s: src/Satr.cpp.s

.PHONY : src/Satr.s

# target to generate assembly for a file
src/Satr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/Satr.cpp.s
.PHONY : src/Satr.cpp.s

src/combination.o: src/combination.cpp.o

.PHONY : src/combination.o

# target to build an object file
src/combination.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/combination.cpp.o
.PHONY : src/combination.cpp.o

src/combination.i: src/combination.cpp.i

.PHONY : src/combination.i

# target to preprocess a source file
src/combination.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/combination.cpp.i
.PHONY : src/combination.cpp.i

src/combination.s: src/combination.cpp.s

.PHONY : src/combination.s

# target to generate assembly for a file
src/combination.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/combination.cpp.s
.PHONY : src/combination.cpp.s

src/dummy_class.o: src/dummy_class.cpp.o

.PHONY : src/dummy_class.o

# target to build an object file
src/dummy_class.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/dummy_class.cpp.o
.PHONY : src/dummy_class.cpp.o

src/dummy_class.i: src/dummy_class.cpp.i

.PHONY : src/dummy_class.i

# target to preprocess a source file
src/dummy_class.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/dummy_class.cpp.i
.PHONY : src/dummy_class.cpp.i

src/dummy_class.s: src/dummy_class.cpp.s

.PHONY : src/dummy_class.s

# target to generate assembly for a file
src/dummy_class.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/dummy_class.cpp.s
.PHONY : src/dummy_class.cpp.s

src/fetch_dict.o: src/fetch_dict.cpp.o

.PHONY : src/fetch_dict.o

# target to build an object file
src/fetch_dict.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/fetch_dict.cpp.o
.PHONY : src/fetch_dict.cpp.o

src/fetch_dict.i: src/fetch_dict.cpp.i

.PHONY : src/fetch_dict.i

# target to preprocess a source file
src/fetch_dict.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/fetch_dict.cpp.i
.PHONY : src/fetch_dict.cpp.i

src/fetch_dict.s: src/fetch_dict.cpp.s

.PHONY : src/fetch_dict.s

# target to generate assembly for a file
src/fetch_dict.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/fetch_dict.cpp.s
.PHONY : src/fetch_dict.cpp.s

src/input.o: src/input.cpp.o

.PHONY : src/input.o

# target to build an object file
src/input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/input.cpp.o
.PHONY : src/input.cpp.o

src/input.i: src/input.cpp.i

.PHONY : src/input.i

# target to preprocess a source file
src/input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/input.cpp.i
.PHONY : src/input.cpp.i

src/input.s: src/input.cpp.s

.PHONY : src/input.s

# target to generate assembly for a file
src/input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/input.cpp.s
.PHONY : src/input.cpp.s

src/levenshtein.o: src/levenshtein.cpp.o

.PHONY : src/levenshtein.o

# target to build an object file
src/levenshtein.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/levenshtein.cpp.o
.PHONY : src/levenshtein.cpp.o

src/levenshtein.i: src/levenshtein.cpp.i

.PHONY : src/levenshtein.i

# target to preprocess a source file
src/levenshtein.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/levenshtein.cpp.i
.PHONY : src/levenshtein.cpp.i

src/levenshtein.s: src/levenshtein.cpp.s

.PHONY : src/levenshtein.s

# target to generate assembly for a file
src/levenshtein.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/levenshtein.cpp.s
.PHONY : src/levenshtein.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utf8_iterator.o: src/utf8_iterator.cpp.o

.PHONY : src/utf8_iterator.o

# target to build an object file
src/utf8_iterator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/utf8_iterator.cpp.o
.PHONY : src/utf8_iterator.cpp.o

src/utf8_iterator.i: src/utf8_iterator.cpp.i

.PHONY : src/utf8_iterator.i

# target to preprocess a source file
src/utf8_iterator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/utf8_iterator.cpp.i
.PHONY : src/utf8_iterator.cpp.i

src/utf8_iterator.s: src/utf8_iterator.cpp.s

.PHONY : src/utf8_iterator.s

# target to generate assembly for a file
src/utf8_iterator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/utf8_iterator.cpp.s
.PHONY : src/utf8_iterator.cpp.s

src/utf8_string.o: src/utf8_string.cpp.o

.PHONY : src/utf8_string.o

# target to build an object file
src/utf8_string.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/utf8_string.cpp.o
.PHONY : src/utf8_string.cpp.o

src/utf8_string.i: src/utf8_string.cpp.i

.PHONY : src/utf8_string.i

# target to preprocess a source file
src/utf8_string.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/utf8_string.cpp.i
.PHONY : src/utf8_string.cpp.i

src/utf8_string.s: src/utf8_string.cpp.s

.PHONY : src/utf8_string.s

# target to generate assembly for a file
src/utf8_string.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rahbar-e-Sukhan.dir/build.make CMakeFiles/Rahbar-e-Sukhan.dir/src/utf8_string.cpp.s
.PHONY : src/utf8_string.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Rahbar-e-Sukhan_autogen"
	@echo "... Rahbar-e-Sukhan"
	@echo "... Rahbar-e-Sukhan_autogen/EWIEGA46WW/qrc_qml.o"
	@echo "... Rahbar-e-Sukhan_autogen/EWIEGA46WW/qrc_qml.i"
	@echo "... Rahbar-e-Sukhan_autogen/EWIEGA46WW/qrc_qml.s"
	@echo "... Rahbar-e-Sukhan_autogen/mocs_compilation.o"
	@echo "... Rahbar-e-Sukhan_autogen/mocs_compilation.i"
	@echo "... Rahbar-e-Sukhan_autogen/mocs_compilation.s"
	@echo "... src/Isqat.o"
	@echo "... src/Isqat.i"
	@echo "... src/Isqat.s"
	@echo "... src/Lafz.o"
	@echo "... src/Lafz.i"
	@echo "... src/Lafz.s"
	@echo "... src/Meter.o"
	@echo "... src/Meter.i"
	@echo "... src/Meter.s"
	@echo "... src/Satoor.o"
	@echo "... src/Satoor.i"
	@echo "... src/Satoor.s"
	@echo "... src/Satr.o"
	@echo "... src/Satr.i"
	@echo "... src/Satr.s"
	@echo "... src/combination.o"
	@echo "... src/combination.i"
	@echo "... src/combination.s"
	@echo "... src/dummy_class.o"
	@echo "... src/dummy_class.i"
	@echo "... src/dummy_class.s"
	@echo "... src/fetch_dict.o"
	@echo "... src/fetch_dict.i"
	@echo "... src/fetch_dict.s"
	@echo "... src/input.o"
	@echo "... src/input.i"
	@echo "... src/input.s"
	@echo "... src/levenshtein.o"
	@echo "... src/levenshtein.i"
	@echo "... src/levenshtein.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utf8_iterator.o"
	@echo "... src/utf8_iterator.i"
	@echo "... src/utf8_iterator.s"
	@echo "... src/utf8_string.o"
	@echo "... src/utf8_string.i"
	@echo "... src/utf8_string.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

